name: Test

on:
  - push

jobs:
  test:
    runs-on: [self-hosted, ubuntu]

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: kuhnroyal/flutter-fvm-config-action@v1
        name: Configure FVM

      - uses: subosito/flutter-action@v2
        name: Install Flutter
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install project dependencies
        run: flutter pub get

      - name: Run code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Check formatting
        run: flutter format --set-exit-if-changed .

      - name: Run static analysis
        run: flutter analyze .

      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random
